### ISSUE TITLE
Question: why not allow more than one instance of rua running?

### ISSUE THREAD

**Issue by VitalyAnkh** [vn971/rua#128]
![image](https://user-images.githubusercontent.com/24508452/83378078-30963500-a40a-11ea-8635-d3f1b58adf28.png)
Sometimes I use rua to install two packages at the same time, so the feature is annoying.

**Comment by vn971** [comment]
Hi. Unfortunately, this issue can't go through. The problem is that the "single instance only" model is really used to ensure no weird breakages in RUA. Without it, any step can break weirdly. E.g. you just prepared to build a directory, and then all contents are gone because another process wiped it. Or you copy the wrong things to the wrong place. Or have two different clients of different versions running in parallel.

"Single instance only", while it is somewhat limiting, allows a very clear understanding of what's happening, has a clearly defined "start" and "end".

Note that any operations that can avoid conflicts with other operations - are allowed to be run in parallel. E.g.: searching, querying information, `shellcheck`, `tarcheck`, checking for upgrades via `--printonly` (but not executing them).

**Comment by VitalyAnkh** [comment]
Thanks!
