### ISSUE TITLE
I am getting the famous `exists in filesystem` error

### ISSUE THREAD

**Issue by refaelsh** [vn971/rua#177]
Hi all,

I am getting the famous `exists in filesystem` error when doing this: `rua install postman-bin`.
Usually, the solution would be to read this part of the Arch Linux wiki: https://wiki.archlinux.org/title/Pacman#.22Failed_to_commit_transaction_.28conflicting_files.29.22_error.
But, the wiki instructs to pass certain parameters to `pacman`. How can I do this when using `rua`?

Thanks all.

**Comment by vn971** [comment]
Hey @refaelsh, what is the exact parameter you thought of adding, at which step? Do you mean the installation step, one that happens after already successfully building a package?

**Comment by refaelsh** [comment]
According to the wiki mentioned in the original post, I am supposed to pass the following parameters to `pacman`: `pacman -S --overwrite glob package`.

**Comment by vn971** [comment]
@refaelsh OK. This doesn't apply to what rua does _directly_, because `pacman -S` means to install a "core", non-aur package. But I get that you mean to pass the `--overwrite` parameter to whatever installation command that is, so `pacman -U` in rua-s case. Would it work for you to just not use the built-in easy `sudo` installation, but manually type (or copy if you work from a graphical terminal) the installation commad?

E.g. rua should print something like that while it installs things:
```txt
[E]=list executable files, [L]=list all files, [T]=run shell to inspect, [O]=ok, proceed. o

Packages need to be installed:

    pacman -U '/home/myuser/.local/share/rua/checked_tars/mypackage/mypackage-2.8.3-1-x86_64.pkg.tar.zst'

Enter S to `sudo` install it, or install manually and press M when done. 
```

At this step, you can also install the package manually, and "press M when done".

Would that be an good-enough solution, what do you think?

**Comment by vn971** [comment]
EDIT -^

**Comment by refaelsh** [comment]
Thank you very much @vn971. I've never really noticed the `M` option. Just tried it, and it worked perfectly. I am closing this issue.

**Comment by vn971** [comment]
@refaelsh Thanks! I want to get to the other issues/MRs as well, but there's a lot, I'm only moving slowly.. Mainly just telling that I still have it in my TODO.

**Comment by refaelsh** [comment]
@vn971 That is perfectly ok, no problem. Thank you for your great Open Source project :-)
