### ISSUE TITLE
Cover -git package when doing upgrade and add update out of date package?

### ISSUE THREAD

**Issue by tmpm697** [vn971/rua#181]
This `rua` lacks of `update` command that update out of date packages from `aur`.

also `rua` doesn't `upgrade` / `update` (if added) packages from aur that ended with `-git`.

users often have some `-git` packages and make no sense to only manage un`-git` packages.

**Comment by vn971** [comment]
Hi! The `-git` handling is explicitly designed this way at the moment. If you want to upgrade "git" packages, see the `rua upgrade --devel` flag and the [limitations](https://github.com/vn971/rua#limitations):

> Development packages such as "-git" packages are only rebuilt when running `rua upgrade --devel`. No version checks are done to avoid unnecessary rebuilds. Merge requests welcomed.

If there's a way to handle the packages in a smart way, merge requests would indeed be welcomed. Note that the problem is actually more difficult than it might seem because, for example, `-git` is only one suffix that designate these types of packages, there could be `-hg` or actually any suffix for that.

If one would want to handle this 100% correctly, looking inside the `sources` would be required, somehow. Some kind of checksums would likely need to be constructed, and a re-build should possibly be triggered when sources change.
